=== experttag/DeployAppFileManagerSolara/src/main/webapp/WEB-INF/smartpool/pool-config.xsd
<?xml version="1.0"?>
<xsd:schema
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        >
    
    <xsd:element name="pool-config">
        <xsd:complexType>
            <xsd:sequence minOccurs="1">
                <xsd:element name="pool" type="pool"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="pool">
        <xsd:sequence>
            <xsd:element name="basic" type="basic" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="connect-strings" type="connect-strings" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="external-pooling" type="external-pooling" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="pool-sizing" type="pool-sizing" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="leak-detection" type="leak-detection" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="basic">
        <xsd:sequence>
            <xsd:element name="pool-name" type="pool-name" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="default-pool" type="default-pool" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="connection-driver" type="connection-driver" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="username" type="username" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="password" type="password" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="auto-close" type="auto-close" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="allow-anonymous-connections" type="allow-anonymous-connections" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="validator-query" type="validator-query" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="pool-sizing">
        <xsd:sequence>
            <xsd:element name="min-connections" type="min-connections" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="max-connections" type="max-connections" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="increment-by" type="increment-by" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="max-free-connections-for-release" type="max-free-connections-for-release" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="connection-wait-time-out" type="connection-wait-time-out" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="max-connection-idle-time" type="max-connection-idle-time" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="connect-strings">
        <xsd:sequence>
            <xsd:element name="thread-stickiness" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="connect-string" type="connect-string" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="external-pooling">
        <xsd:sequence>
            <xsd:element name="thread-stickiness" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="connection-loader-class" type="connection-loader-class" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="leak-detection">
        <xsd:sequence>
            <xsd:element name="detect-leaks" type="detect-leaks" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="leak-time-out" type="leak-time-out" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="poll-thread-time" type="poll-thread-time" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="default-listener" type="default-listener" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="pool-name" >
        <xsd:restriction base="xsd:string">
            <xsd:minLength  value="0"/>
            <xsd:maxLength  value="255"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="connection-driver" >
        <xsd:restriction base="xsd:string">
            <xsd:minLength  value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="min-connections" >
        <xsd:restriction base="xsd:long">
            <xsd:minInclusive  value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="max-connections" >
        <xsd:restriction base="xsd:long">
            <xsd:minInclusive  value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="increment-by" >
        <xsd:restriction base="xsd:long">
            <xsd:minInclusive  value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="username" >
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>

    <xsd:simpleType name="password" >
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>

    <xsd:simpleType name="validator-query" >
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>


    <xsd:simpleType name="connect-string" >
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="connection-loader-class" >
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>

    <xsd:simpleType name="default-pool" >
        <xsd:restriction base="xsd:boolean"/>
    </xsd:simpleType>

    <xsd:simpleType name="detect-leaks" >
        <xsd:restriction base="xsd:boolean"/>
    </xsd:simpleType>

    <xsd:simpleType name="leak-time-out" >
        <xsd:restriction base="xsd:long">
            <xsd:minInclusive  value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="poll-thread-time" >
        <xsd:restriction base="xsd:long">
            <xsd:minInclusive  value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="auto-close" >
        <xsd:restriction base="xsd:boolean"/>
    </xsd:simpleType>

    <xsd:simpleType name="allow-anonymous-connections" >
        <xsd:restriction base="xsd:boolean"/>
    </xsd:simpleType>

    <xsd:simpleType name="max-free-connections-for-release" >
        <xsd:restriction base="xsd:long">
            <xsd:minInclusive  value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="connection-wait-time-out" >
        <xsd:restriction base="xsd:long">
            <xsd:minInclusive  value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="max-connection-idle-time" >
        <xsd:restriction base="xsd:long">
            <xsd:minInclusive  value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="default-listener" >
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>


</xsd:schema>

=== experttag/DeployAppFileManagerSolara/src/main/webapp/WEB-INF/smartpool/pool-config.xml
<?xml version="1.0" encoding="utf-8" ?>

<!-- This is a sample config file illustrating most of the common usages -->

<!-- The pool-config.xsd is expected to be in the same directory as the xml file, edit to absolute location if required -->

<pool-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pool-config.xsd">

    <!-- A Pool named Pool_One -->
    <pool>

        <!-- Basic pool configuration -->
        <basic>

            <!-- Name of the pool, should be a unique name -->
            <pool-name>SolaraPool</pool-name>

            <!-- This pool is the default pool, indicating you dont need to specify the name of the pool when fetching a connection -->
            <default-pool>true</default-pool>

            <!-- Name of the driver, should be in classpath -->
            <connection-driver>com.mysql.jdbc.Driver</connection-driver>

            <!-- database username -->
            <username>artsansa_sola</username>

            <!-- database password -->
            <password>artsansa_sola</password>

            <!-- SmartPool will automatically close the objects like Statment, PreparedStatement, CallableStatement when
            connection is returned to pool, default is false -->
            <auto-close>true</auto-close>

            <!-- Users will be allowed to obtain a connection from this pool without specifying an owner, default is false -->
            <allow-anonymous-connections>true</allow-anonymous-connections>

            <!-- Run this query to validate a connection before the connection is handed over to the user -->
            <validator-query>select count(*) from pnrstatus</validator-query>

        </basic>
        <!--End of Basic pool configuration -->


        <!-- Specify connect string, this section is to support multiple subpools whitin a single pool, thus allowing load balacing withing a pool.
        This feature is particularly usefull in a clustered database environment like Oracle RAC where multiple instances can be used to
        access the same database. The pool will contain Subpools each pooling connections from the connect-string specified -->
        <connect-strings>
            <!-- The thread will be associated with a sub pool, so that all connections drawn from the same thread will be served
            by the same instance, this is to avoid the problems of distributed transactions spawning across differnt databases in a cluster.
            -->
            <thread-stickiness>true</thread-stickiness>
            <!-- Connect string for the subpool -->
            <connect-string name="conn1">jdbc:mysql://localhost:3306/artsansa_solara</connect-string>
            <!--connect-string name="conn1">jdbc:mysql://localhost:3307/artsansar</connect-string-->
        </connect-strings>


        <!-- Pool Sizing parameters -->
        <pool-sizing>
            <!-- Minimum connections in the pool -->
            <min-connections>2</min-connections>

            <!-- Maximum connections in the pool -->
            <max-connections>10</max-connections>

            <!-- Increment number when no more free connections are available -->
            <increment-by>1</increment-by>

            <!-- Maximum no of free connections to be available for the pool to shrink -->
            <max-free-connections-for-release>2</max-free-connections-for-release>

            <!-- Allowed wait time before an exception is thrown to the user while waiting
            for a free connections is available -->
            <connection-wait-time-out>100</connection-wait-time-out>

            <!-- Maximum allowed idle time, after which a connection is recovered forcefully -->
            <max-connection-idle-time>1000</max-connection-idle-time>

        </pool-sizing>
        <!-- End of Pool Sizing parameters -->


        <!-- Leak Detection section -->
        <leak-detection>

            <!-- Turn Leak detection on/off -->
            <detect-leaks>true</detect-leaks>

            <!-- Allowed time for a user to hold a connection after which it is categorised as a leak -->
            <leak-time-out>100</leak-time-out>

            <!-- The poll interval of the thread that does the leak detection -->
            <poll-thread-time>1000</poll-thread-time>

            <!-- The listener that listens to leak events -->
            <default-listener>org.smartlib.impl.LeakDetectorImpl</default-listener>

        </leak-detection>
        <!-- Leak Detection section -->

    </pool>



</pool-config>
